version: '3.8'

services:
  app:
    image: taregsafi/location-attitude-longitude:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENCAGE_API_KEY=${OPENCAGE_API_KEY}
    ports:
      - "8081:8081"
    volumes:
      - ./data/GZ_GPS.txt:/data/GZ_GPS.txt
